// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Mon May 26 21:35:10 2014

Mandelbrot Mandelbrot_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.start(start_sig) ,	// input  start_sig
	.cx(cx_sig) ,	// input [W-1:0] cx_sig
	.cy(cy_sig) ,	// input [W-1:0] cy_sig
	.max_it(max_it_sig) ,	// input [15:0] max_it_sig
	.iter(iter_sig) ,	// output [15:0] iter_sig
	.idler(idler_sig) 	// output  idler_sig
);

defparam Mandelbrot_inst.W = 32;
defparam Mandelbrot_inst.M = 4;
