// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Tue May 27 00:40:57 2014

snes_controller snes_controller_inst
(
	.clk_166MHz(clk_166MHz_sig) ,	// input  clk_166MHz_sig
	.sclk(sclk_sig) ,	// output  sclk_sig
	.latch(latch_sig) ,	// output  latch_sig
	.datain(datain_sig) ,	// input  datain_sig
	.start(start_sig) ,	// input  start_sig
	.finish(finish_sig) ,	// output  finish_sig
	.boton_B(boton_B_sig) ,	// output  boton_B_sig
	.boton_Y(boton_Y_sig) ,	// output  boton_Y_sig
	.boton_SELECT(boton_SELECT_sig) ,	// output  boton_SELECT_sig
	.boton_START(boton_START_sig) ,	// output  boton_START_sig
	.boton_UP(boton_UP_sig) ,	// output  boton_UP_sig
	.boton_DOWN(boton_DOWN_sig) ,	// output  boton_DOWN_sig
	.boton_LEFT(boton_LEFT_sig) ,	// output  boton_LEFT_sig
	.boton_RIGHT(boton_RIGHT_sig) ,	// output  boton_RIGHT_sig
	.boton_A(boton_A_sig) ,	// output  boton_A_sig
	.boton_X(boton_X_sig) ,	// output  boton_X_sig
	.boton_L(boton_L_sig) ,	// output  boton_L_sig
	.boton_R(boton_R_sig) 	// output  boton_R_sig
);

