	system u0 (
		.alt_vip_itc_0_clocked_video_vid_clk       (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),       // alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data      (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),      //                            .vid_data
		.alt_vip_itc_0_clocked_video_underflow     (<connected-to-alt_vip_itc_0_clocked_video_underflow>),     //                            .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>), //                            .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),    //                            .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),    //                            .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f         (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),         //                            .vid_f
		.alt_vip_itc_0_clocked_video_vid_h         (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),         //                            .vid_h
		.alt_vip_itc_0_clocked_video_vid_v         (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),         //                            .vid_v
		.analog1_x_export                          (<connected-to-analog1_x_export>),                          //                   analog1_x.export
		.analog1_y_export                          (<connected-to-analog1_y_export>),                          //                   analog1_y.export
		.analog2_x_export                          (<connected-to-analog2_x_export>),                          //                   analog2_x.export
		.analog2_y_export                          (<connected-to-analog2_y_export>),                          //                   analog2_y.export
		.boton_a_export                            (<connected-to-boton_a_export>),                            //                     boton_a.export
		.boton_b_export                            (<connected-to-boton_b_export>),                            //                     boton_b.export
		.boton_down_export                         (<connected-to-boton_down_export>),                         //                  boton_down.export
		.boton_l_export                            (<connected-to-boton_l_export>),                            //                     boton_l.export
		.boton_left_export                         (<connected-to-boton_left_export>),                         //                  boton_left.export
		.boton_r_export                            (<connected-to-boton_r_export>),                            //                     boton_r.export
		.boton_right_export                        (<connected-to-boton_right_export>),                        //                 boton_right.export
		.boton_up_export                           (<connected-to-boton_up_export>),                           //                    boton_up.export
		.boton_x_export                            (<connected-to-boton_x_export>),                            //                     boton_x.export
		.boton_y_export                            (<connected-to-boton_y_export>),                            //                     boton_y.export
		.clk_clk                                   (<connected-to-clk_clk>),                                   //                         clk.clk
		.epcs_dclk                                 (<connected-to-epcs_dclk>),                                 //                        epcs.dclk
		.epcs_sce                                  (<connected-to-epcs_sce>),                                  //                            .sce
		.epcs_sdo                                  (<connected-to-epcs_sdo>),                                  //                            .sdo
		.epcs_data0                                (<connected-to-epcs_data0>),                                //                            .data0
		.pio_led_green_export                      (<connected-to-pio_led_green_export>),                      //               pio_led_green.export
		.pio_sw_export                             (<connected-to-pio_sw_export>),                             //                      pio_sw.export
		.reset_reset_n                             (<connected-to-reset_reset_n>),                             //                       reset.reset_n
		.sdram_addr                                (<connected-to-sdram_addr>),                                //                       sdram.addr
		.sdram_ba                                  (<connected-to-sdram_ba>),                                  //                            .ba
		.sdram_cas_n                               (<connected-to-sdram_cas_n>),                               //                            .cas_n
		.sdram_cke                                 (<connected-to-sdram_cke>),                                 //                            .cke
		.sdram_cs_n                                (<connected-to-sdram_cs_n>),                                //                            .cs_n
		.sdram_dq                                  (<connected-to-sdram_dq>),                                  //                            .dq
		.sdram_dqm                                 (<connected-to-sdram_dqm>),                                 //                            .dqm
		.sdram_ras_n                               (<connected-to-sdram_ras_n>),                               //                            .ras_n
		.sdram_we_n                                (<connected-to-sdram_we_n>),                                //                            .we_n
		.touch_panel_busy_export                   (<connected-to-touch_panel_busy_export>),                   //            touch_panel_busy.export
		.touch_panel_penirq_n_export               (<connected-to-touch_panel_penirq_n_export>),               //        touch_panel_penirq_n.export
		.touch_panel_spi_MISO                      (<connected-to-touch_panel_spi_MISO>),                      //             touch_panel_spi.MISO
		.touch_panel_spi_MOSI                      (<connected-to-touch_panel_spi_MOSI>),                      //                            .MOSI
		.touch_panel_spi_SCLK                      (<connected-to-touch_panel_spi_SCLK>),                      //                            .SCLK
		.touch_panel_spi_SS_n                      (<connected-to-touch_panel_spi_SS_n>)                       //                            .SS_n
	);

