// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Sat Dec 12 23:36:24 2015

mult_add mult_add_inst
(
	.dataa_0(dataa_0_sig) ,	// input [31:0] dataa_0_sig
	.dataa_1(dataa_1_sig) ,	// input [31:0] dataa_1_sig
	.dataa_2(dataa_2_sig) ,	// input [31:0] dataa_2_sig
	.datab_0(datab_0_sig) ,	// input [31:0] datab_0_sig
	.datab_1(datab_1_sig) ,	// input [31:0] datab_1_sig
	.datab_2(datab_2_sig) ,	// input [31:0] datab_2_sig
	.result(result_sig) 	// output [65:0] result_sig
);

