// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Sat Dec 12 23:18:59 2015

sub_v sub_v_inst
(
	.ax(ax_sig) ,	// input [31:0] ax_sig
	.ay(ay_sig) ,	// input [31:0] ay_sig
	.az(az_sig) ,	// input [31:0] az_sig
	.bx(bx_sig) ,	// input [31:0] bx_sig
	.by(by_sig) ,	// input [31:0] by_sig
	.bz(bz_sig) ,	// input [31:0] bz_sig
	.cx(cx_sig) ,	// output [31:0] cx_sig
	.cy(cy_sig) ,	// output [31:0] cy_sig
	.cz(cz_sig) 	// output [31:0] cz_sig
);

